config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:index, :create, :new] do
    get "/new", to: "users#new"
    post '/new', to: "users#create", as: 'users_create'
    # get '/users', to: "users#index"
    get '/downloads', to: "users#downloads"
    get '/post', to: "users#post"
    member do
      patch :ban
    end
  end


  root "articles#index"

  resources :articles do
    resources :comments
    # match '/users',   to: 'users#index',   via: 'get'
  end

  resources :articles do
    resources :likes
  end
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope {order(created_at: :desc)}
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  include Visible

  def latest_comment
    comments.order('created_at DESC').first
  end

  validates :title, presence: false
  validates :body, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  add_flash_types :info, :error, :warning


  def index
    @articles = Article.all
    @articles1 = Article.new
    @users = User.all
  end



  def show
    @article = Article.find(params[:id])
    # @articles1 = Article.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    # binding.pry

    if @article.save
      flash[:success] = "You have created your post successfully"
      redirect_to root_path
    else
      # puts @article.errors
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
    flash[:success] = "You have edited your post successfully"
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "You have updated your post successfully"
      redirect_to root_path
    else
      flash[:error] = "Post could not be updated"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "You have deleted the post successfully"

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:user_id, :title, :body, :status)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>

<%# <div>
    <%= form.label :title %><br>
    <%# <%= form.text_field :title %>
    <%# <% article.errors.full_messages_for(:title).each do |message| %> 
      <%# <div><%= message %>
    <%# <% end %>
  <%# </div>   %>
  <div>
    <div class="poststatus">
<!--      <%#= form.label :status %><br>-->
      <%= form.select :status, ['public', 'private'], selected: 'public' %>
    </div>
  <div class="body">
    <%# <%= form.label :body %>

    <div class="box">
    <%= form.text_field :body, placeholder: "What's happening?" %>
    </div>
    <br>
    <br>
    <div class="subtexts">
      <%=image_tag("videoIcon.png")%>
     <div class="livevideo">Live video</div>
    <div class="photo"><%=image_tag("photoIcon.png")%>Photo/Video</div>
    <div class="feeling"><%=image_tag("smileyIcon.png")%>Feeling</div>
    </div>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>
    <div class="button">
      <%= form.submit "post" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="Header">
  <div class="headCont">
    <h1 style="font-family:Inria Sans;"><%= image_tag("Vector1.png") %> <%= image_tag("Maze.png") %></h1>
  </div>

  <div class="place">
    <input class="form-control" placeholder="Search for something here..."/>
  </div>
</div>

<div class="Main_Body">
<%= render "form", article: @article %>
<%# redirect_to root_path %>

  <div class="editlink"><%= link_to 'Cancel Edit', articles_path %></div>
</div>

app/views/articles/index.html.erb
<% flash.each do |name,msg| %>
  <div class="alert alert-<%= name %>"><%= msg %></div>
<% end %>


<%#= t "users.first_name" %>

<div class="boundary container">
  <div class="hello">
    <div class="hellomaze">


      <div class="headCont">
        <h1 style="font-family:Inria Sans;"><%= link_to image_tag("Vector1.png"), articles_path %> <%= link_to image_tag("Maze.png"), articles_path %></h1>

      </div>
      <div class="curruser"><span><%= current_user.first_name %> <%= current_user.last_name %>
      <%=  "(Admin)" if current_user.has_role? :admin %>
      </span></div>

      <br>

      <div class="feed">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("feeeed.png") %><%= link_to "Feed", articles_path %></button>
      </div>

      <br>

      <div class="profile">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Profile", edit_user_registration_path %></button>
      </div>

      <br>

      <% if current_user.has_role? :admin %>
      <div class="manage">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("mng.png") %><%= link_to "Manage User", users_path %></button>
      </div>

        <br>

        <div class="report">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("report.png") %><%= link_to "Reports", user_downloads_path(@users) %></button>
        </div>
        <% end %>

      <br>

      <div class="logout">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("logarrow.png") %>
          <%= link_to "Logout", destroy_user_session_path, 'data-turbo-method': :delete %></button>
      </div>

      <div class="interface">
        <div class="Header">
          <div class="place">
            <input class="form-control" placeholder="Search for something here..."/>
          </div>
        </div>
        <br>
        <div class="userandmain">



        <div class="Main_Body">
          <br>
          <div class="subheading">
            <div class="subimage"><%= image_tag("Vector1.png") %></div>
            <%= render "form", article: @articles1 %>
          </div>

          <br>


          <% @articles.each do |article| %>
            <%# unless article.private? %>
            <%# unless article.archived? %>



            <% if current_user.has_role? :admin %>
              <% if article.status == "public" || article.status == "private" %>
                <div class="contentt" style="font-family:Montserrat;">
                  <div class="card-body">

                    <div class="usertitle">
                      <%= image_tag("Vector1.png") %>


                      <div class="currentuser"> <%= article.user.first_name %> </div>


                      <%# dropdown hai ye %>
                      <div class="dropdown">
                        <button class="dropbtn">...</button>

                        <div class="dropdown-content">
                          <%= link_to "Edit", edit_article_path(article) %>
                          <%= link_to "Destroy", article_path(article), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
                        </div>

                      </div>
                      <%# dropdown khtm %>
                    </div>

                    <div class="timestamp"><%= time_ago_in_words(article.created_at) %> ago ,
                      <span><%= article.status %></span></div>

                    <br>

                    <div class="card-text" style=" font-weight: 300;  font-family: system-ui; font-size: 14px;">

                      <hr>

                      <%= article.body %>
                    </div>

                    <br>
                    <br>

                    <div class="noofcomments"> <p><%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes'%> |
                      <%= article.comments.size %>&nbsp;comments </p>
                    </div>

                    <hr>

                    <div class="likecomment">
                      <div class="likeimage">
                        <% pre_like = article.likes.find { |like| like.user_id == current_user.id} %>
                        <% if pre_like %>
                        <div class="likepng"><%= image_tag("like.png") %>
                          <%= button_to 'Unlike', article_like_path(article, pre_like), method: :delete %></div>
                        <% else %>
                          <div class="likepng"><%= image_tag("like.png") %><%= button_to 'Like', article_likes_path(article), method: :post %></div>
                        <% end %>


                      </div> &nbsp;&nbsp;&nbsp;

                      <div class="commentimage">
                        <%= image_tag("comment.png") %>
                        <div class="commenttext"><%= link_to "Comments", article, data: { turbolinks: false }, :method => "get" %></div>
                      </div>&nbsp;&nbsp;&nbsp;
                    </div>

                    <hr>

                    <br>

                    <div class="comm">
                      <% @article = article %>
                      <%= render 'comments/form' %>
                    </div>

                    <hr>

                    <div class="mostrecent"><%= current_user.first_name %>
                      : <%= article.comments.order("created_at DESC").first&.body %></div>

                  </div>
                </div>

              <% end %>

            <% else %>
                 <% if current_user.id == article.user_id || article.status == "public" %>
                <div class="contentt" style="font-family:Montserrat;">
                  <div class="card-body">

                    <div class="usertitle">
                      <%= image_tag("Vector1.png") %>
                      <div class="currentuser"> <%= article.user.first_name %> </div>

                      <%# dropdown hai ye %>
                      <div class="dropdown">
                        <button class="dropbtn">...</button>
                        <div class="dropdown-content">
                          <%= link_to "Edit", edit_article_path(article) %>
                          <%= link_to "Destroy", article_path(article), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
                        </div>
                      </div>
                      <%# dropdown khtm %>
                    </div>

                    <div class="timestamp"><%= time_ago_in_words(article.created_at) %> ago ,
                      <span><%= article.status %></span></div>


                    <br>

                    <div class="card-text" style=" font-weight: 300;  font-family: system-ui; font-size: 14px;">
                      <hr>
                      <%= article.body %>
                    </div>

                    <br>
                    <br>

                    <div class="noofcomments"><%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes'%> |
                      <%= article.comments.size %>&nbsp;comments
                    </div>

                    <hr>

                    <div class="likecomment">
                      <div class="likeimage">
                        <div class="likepng"></div>
                        <% pre_like = article.likes.find { |like| like.user_id == current_user.id} %>
                        <% if pre_like %>
                          <div class="likepng"><%= image_tag("like.png") %>
                            <%= button_to 'Unlike', article_like_path(article, pre_like), method: :delete %></div>
                        <% else %>
                          <div class="likepng"><%= image_tag("like.png") %><%= button_to 'Like', article_likes_path(article), method: :post %></div>
                        <% end %>
                      </div> &nbsp;&nbsp;&nbsp;
                      <div class="commentimage">
                        <%= image_tag("comment.png") %>
                        <div class="commenttext"><%= link_to "Comments", article, data: { turbolinks: false }, :method => "get" %></div>
                      </div>&nbsp;&nbsp;&nbsp;
                    </div>

                    <hr>

                    <br>

                    <div class="comm">
                      <% @article = article %>
                      <%= render 'comments/form' %>
                    </div>

                    <hr>

                    <div class="mostrecent">
                      <%= article.comments.order("created_at DESC").first&.body %></div>

                  </div>
                </div>

              <% end %>

            <% end %>



            <%# end %>

            <br>

          <% end %>
        </div>

          <% if current_user.has_role? :admin %>
            <div class="userlist">
              <div class="alluserss"><%= image_tag("Users List.png") %></div>
              <br>
              <% @users.each do |user| %>
                <% if user.articles.present? %>
                <div class="usernames"><%= image_tag("mazesmall.png") %>&nbsp;<%= user.first_name %><%= user.last_name %></div>
                  <br>

                  <% end %>
              <% end %>
          <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="Header">
  <div class="headCont">
    <h1 style="font-family:Inria Sans;"><%= image_tag("Vector1.png") %> Maze</h1>
  </div>

  <div class="place">
    <input class="form-control" placeholder="Search for something here..."/>
  </div>
</div>

<div class="Main_Body">
<%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<!--<div class="col">-->
<div class="Header">
  <div class="headCont">
    <h1 style="font-family:Inria Sans;"><%= link_to image_tag("Vector1.png"), articles_path %> <%= link_to image_tag("Maze.png"), articles_path %></h1>
    <div class="place">
      <input class="form-control" placeholder="Search for something here..."/>
    </div>
  </div>


</div>


  <div class="Main_Body">
    <div class="nestedmain">
    <div class="mainn">



    <%# dropdown hai ye %>
      <div class="dropdown">
        <button class="dropbtn">...</button>
        <div class="timestamp"><%= time_ago_in_words(@article.created_at) %> ago</div>
        <div class="dropdown-content">
          <%= link_to "Edit", edit_article_path(@article) %>
          <%= link_to "Destroy", article_path( @article), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
        </div>
      </div>
    <%# dropdown khtm %>
<div class="showcomments"><%= @article.body %></div>
    <br>
    <div class="noofcomments">1 like |
      <%= @article.comments.size %>&nbsp;comments</div>

    <hr>





<h2>Comments</h2>
    <hr>
<% @article.comments.each do |comment| %>


        <div class="commentinguser"><%= comment.user.first_name %> :
  <div class="commentbody">
    <%= comment.body %>
    <div class="timestamp">Posted <%= time_ago_in_words(comment.created_at) %> ago</div>
    <div class="downn">
<!--      <button class="dropbtncomment">...</button>-->
      <div class="dropdown-content-comment">
        <%= link_to "Delete", article_comment_path(comment.article, comment), remote: true, data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure to delete the comment?"
        } %>
      </div>
    </div>

    <hr>



  </div>
        </div>
<% end %>

      <div class="commentform"><%= render 'comments/form' %></div>


</div>
  </div>
  </div>
<!--</div>-->