config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:index, :create, :new] do
    get "/new", to: "users#new"
    post '/new', to: "users#create", as: 'users_create'
    # get '/users', to: "users#index"
    get '/downloads', to: "users#downloads"
    get '/post', to: "users#post"
    member do
      patch :ban
    end
  end


  root "articles#index"

  resources :articles do
    resources :comments
    # match '/users',   to: 'users#index',   via: 'get'
  end

  resources :articles do
    resources :likes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # validate :must_have_a_role, on: :update
  # acts_as_xlsx :columns => [:User]
  require 'csv'
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :phone, :presence => { :message => 'hello world, bad operation!' }, :numericality => true, :length => { :minimum => 10, :maximum => 10 }

  def self.to_index
    CSV.generate(col_sep: ";") do |csv|
      csv << ["FIRST NAME", "LAST NAME", "POST", "COMMENTS", "LIKES COUNT"]
      all.each do |record|
        record.articles.each do |article|
          article.comments.each do |com|
            csv << [record.first_name, record.last_name, article.body, com.body, article.likes.count]
          end
        end
      end
    end
  end

  def self.to_indexx
    package = Axlsx::Package.new
    workbook = package.workbook
      workbook.add_worksheet(:name => "User") do |sheet|
        all.each do |user|
          user.articles.each do |article|
            article.comments.each do |com|
              sheet.add_row [user.first_name, user.last_name, article.body, com.body, article.likes.count]
            end
          end
        end
        # %w(first second third).each { |label| sheet.add_row [label, rand(24)+1] }
        # sheet.add_chart(Axlsx::Pie3DChart, :start_at => [0,5], :end_at => [10, 20], :title => "example 3: Pie Chart") do |chart|
        #   chart.add_series :data => sheet["B2:B4"], :labels => sheet["A2:A4"],  :colors => ['FF0000', '00FF00', '0000FF']
      end
      # p.serialize('User.xlsx')
      package.to_stream.read
    end

  def self.to_download
    CSV.generate(col_sep: ";") do |csv|
      csv << ["FIRST NAME", "LAST NAME", "POST", "COMMENTS", "LIKES COUNT"]
      all.find_each do |record|
        if record.articles.count > 3
          record.articles.each do |article|
            article.comments.each do |com|
              csv << [record.first_name, record.last_name, article.body, com.body, article.likes.count]
            end
          end
        end
      end
    end
  end

  def self.to_downloads
    package = Axlsx::Package.new
    workbook = package.workbook
    workbook.add_worksheet(:name => "User") do |sheet|
      all.each do |user|
        if user.articles.count > 3
        user.articles.each do |article|
          article.comments.each do |com|
            sheet.add_row [user.first_name, user.last_name, article.body, com.body, article.likes.count]
          end
        end
      end
      # %w(first second third).each { |label| sheet.add_row [label, rand(24)+1] }
      # sheet.add_chart(Axlsx::Pie3DChart, :start_at => [0,5], :end_at => [10, 20], :title => "example 3: Pie Chart") do |chart|
      #   chart.add_series :data => sheet["B2:B4"], :labels => sheet["A2:A4"],  :colors => ['FF0000', '00FF00', '0000FF']
    end
    # p.serialize('User.xlsx')

    end
    package.to_stream.read
    end

  def self.to_post
    CSV.generate(col_sep: ";") do |csv|
      csv << ["TITLE", "POST", "COMMENTS", "LIKES COUNT"]
      all.find_each do |record|
        record.articles.each do |article|
          article.comments.each do |com|
            csv << [record.first_name, article.body, com.body, article.likes.count]
          end
        end
      end
    end
  end

  def self.to_posts
    package = Axlsx::Package.new
    workbook = package.workbook
    workbook.add_worksheet(:name => "User") do |sheet|
      all.each do |user|
          user.articles.each do |article|
            article.comments.each do |com|
              sheet.add_row [user.first_name, article.body, com.body, article.likes.count]
            end
          end
        end
        # %w(first second third).each { |label| sheet.add_row [label, rand(24)+1] }
        # sheet.add_chart(Axlsx::Pie3DChart, :start_at => [0,5], :end_at => [10, 20], :title => "example 3: Pie Chart") do |chart|
        #   chart.add_series :data => sheet["B2:B4"], :labels => sheet["A2:A4"],  :colors => ['FF0000', '00FF00', '0000FF']
      end
      # p.serialize('User.xlsx')
    package.to_stream.read
    end

  # validate :has_valid_email?
  #
  # VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  #
  # def has_valid_email
  #   self.email =~ VALID_EMAIL_REGEX
  # end

  # private
  # def must_have_a_role
  #   unless roles.any?
  #     errors.add(:roles, "must have at least one role")
  #   end
  # end

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :lockable
end

app/controllers/users_controller.rb
# require 'csv'
class UsersController < ApplicationController

  def index
    @users = User.all
    @articles=Article.all

    respond_to do |format|
      # format.xlsx
      format.xlsx do
        send_data User.to_indexx
      end
      format.csv do
        send_data User.to_index, filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  def downloads
    @users = User.all
    # @articles=Article.all
    respond_to do |format|
      format.html
      # format.xlsx
      format.xlsx do
              send_data User.to_downloads
            end
      format.csv do
        send_data User.to_post, filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  def post
    @users = User.all
    @articles=Article.all
    respond_to do |format|
      format.html
      # format.xlsx
      format.xlsx do
        send_data User.to_posts
      end
      format.csv do
        send_data User.to_post, filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  def new

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
      flash[:notice] = "User has been created"   #there you are!!!
    else
      # puts @article.errors
      # flash[:alert] = "Something went wrong ..."   # ah! again, there you are!!!
      redirect_to registration_path, info: "Invalid email or password"
    end
  end

  def ban
    @user = User.find(params[:id])
    if @user.access_locked?
      @user.unlock_access!
    else
      @user.lock_access!
    end
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/downloads.html.erb
<div class="boundary container">
  <div class="headCont">
    <h1 style="font-family:Inria Sans;"><%= link_to image_tag("Vector1.png"), articles_path %> <%= link_to image_tag("Maze.png"), articles_path %></h1>

    <div class="Header">
      <div class="place">
        <input class="form-control" placeholder="Search for something here..."/>
      </div>
    </div>


  </div>
  <!--  <div class="sidenav">-->
  <div class="csvmainnav">
    <div class="csvnav">
      <div class="feed">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("feed.png") %><%= link_to "Feed", articles_path %></button>
      </div>

      <br>

      <div class="profile">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Profile", edit_user_registration_path %></button>
      </div>

      <br>


      <div class="manage">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Manage User", users_path %></button>
      </div>
      <br>

      <div class="report">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("report.png") %><%= link_to "Reports" %></button>
      </div>

      <br>

      <div class="logout">
        <button type="button" class="btn btn-outline-primary"><%= image_tag("logarrow.png") %><%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } %></button>
      </div>
    </div>

    <div class="downloadoptions">
      <div class="allusers">
        <div class="allusercontent">
          <br>
          <div class="icon"><%= image_tag("file.png") %></div>
<!--            <div class="backclass"><%#= image_tag("back.png")  %></div>-->
          <br>
        <div class="userhead">All users</div>
        <div class="subhead">Post,comments and likes count</div>
        <br>
          <input  type="radio" name="download" value="CSV" /> CSV &nbsp;
          <input  type="radio" name="download" value="CSV" /> EXCEL
        <div class="downlink"><%= link_to "CSV", users_path(format: :csv), class: "btn btn-primary" %>

        <%= link_to 'EXCEL', users_path(format: :xlsx), class: "btn btn-primary" %></div>
        </div>
      </div>

      <div class="morethan3">
        <div class="morethan3content">
          <br>
          <div class="icon"><%= image_tag("file.png") %></div>
<!--            <div class="backclass"><%#= image_tag("back.png")  %></div>-->
          <br>
        <div class="userhead">All users</div>
        <div class="subhead">Having more than 3 posts</div>
        <br>
          <input  type="radio" name="download" value="CSV" /> CSV &nbsp;
          <input  type="radio" name="download" value="CSV" /> EXCEL
        <div class="downlink"><%= link_to "CSV", user_downloads_path(format: :csv), class: "btn btn-primary" %>
        <%= link_to 'EXCEL', user_downloads_path(format: :xlsx), class: "btn btn-primary" %></div>
        </div>
      </div>

      <div class="postwise">
        <div class="postwisecontent">
          <br>
          <div class="icon"><%= image_tag("file.png") %></div>
<!--        <div class="backclass"><%#= image_tag("back.png") %></div>-->
          <br>
        <div class="posthead">Postwise Report</div>
        <div class="subhead">Title/Description,comments,likes</div>
        <br>
          <input  type="radio" name="download" value="CSV" /> CSV &nbsp;
          <input  type="radio" name="download" value="CSV" /> EXCEL
        <div class="downlink"><%= link_to "CSV", user_post_path(format: :csv), class: "btn btn-primary" %>
        <%= link_to 'EXCEL', user_post_path(format: :xlsx), class: "btn btn-primary" %></div>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/users/index.html.erb
<% flash.each do |name,msg| %>
  <div class="alert alert-<%= name %>"><%= msg %></div>
<% end %>
<div class="boundary container">
<div class="headCont">
  <h1 style="font-family:Inria Sans;"><%= link_to image_tag("Vector1.png"), articles_path %> <%= link_to image_tag("Maze.png"), articles_path %></h1>
  <div class="usermanage"><%= image_tag("User Management.png") %></div>

</div>
<!--  <div class="sidenav">-->
    <div class="feed">
      <button type="button" class="btn btn-outline-primary"><%= image_tag("feed.png") %><%= link_to "Feed", articles_path %></button>
    </div>

    <br>

    <div class="profile">
      <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Profile", edit_user_registration_path %></button>
    </div>

    <br>


    <div class="manage">
      <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Manage User", users_path %></button>
    </div>
  <br>

  <div class="report">
    <button type="button" class="btn btn-outline-primary"><%= image_tag("report.png") %><%= link_to "Reports" %></button>
  </div>

    <br>

    <div class="logout">
      <button type="button" class="btn btn-outline-primary"><%= image_tag("logarrow.png") %><%= link_to "Logout", destroy_user_session_path,  data: {"turbo-method": :delete} %></button>
    </div>





  <div class="usermain"><div class="listofusers"><%= image_tag("List of Users.png") %>
    <div class="createroles"><%= link_to "Create role", user_new_path(@users) ,class:"btn btn-primary" %></div>
    <br>
    <br>
<!--    <div class="usermain">-->
      <% @users.each do |user| %>
        <div class="userindexlist">
          <div class="iconwithname"><%= image_tag("mazesmall.png") %><%= user.first_name %></div>
<!--          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
          <div class="userphone"><%= user.phone %></div>
<!--          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
          <div class="useremail"><%= user.email %></div>
<!--          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
          <%#= user.access_locked? %>

          <!--                  <strong>access locked?</strong>-->
          <% if user.access_locked? %>
            <div class="activebutton"><%= button_to "Activate", ban_user_path(user), method: :patch  %></div>
            <% else %>
            <div class="deactive"><%= button_to "Deactivate", ban_user_path(user), method: :patch %></div>

          <% end %>



          <br>
        </div>
          <br>
          <br>
<!--      <div class="export"><%#= button_to "Export", user_export_path(user), method: :get  %></div>-->
<% end %>
    </div>
<!--  </div>-->

  </div>


<!--  </div>-->



</div>

app/views/users/new.html.erb
<div class="boundary container">
  <div class="headCont">
    <h1 style="font-family:Inria Sans;"><%= link_to image_tag("Vector1.png"), articles_path %> <%= link_to image_tag("Maze.png"), articles_path %></h1>
    <div class="usermanage"><%= image_tag("User Management.png") %></div>

  </div>

  <div class="userroles">


    <div class="navigation">
      <div class="navitems">
        <div class="feed">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("feed.png") %><%= link_to "Feed", articles_path %></button>
        </div>

        <br>

        <div class="profile">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Profile", edit_user_registration_path %></button>
        </div>

        <br>


        <div class="manage">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("profile.png") %><%= link_to "Manage User", users_path %></button>
        </div>

        <br>

        <div class="report">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("report.png") %><%= link_to "Report User" %></button>
        </div>

        <br>

        <div class="logout">
          <button type="button" class="btn btn-outline-primary"><%= image_tag("logarrow.png") %><%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } %></button>
        </div>
      </div>

      <div class="addingusers">
        <%= image_tag("Add Users.png") %>

<!--        <div class="admincontrol"-->
        <%= form_with url: user_users_create_path, model:@user do |form| %>

          <br>

          <div class="admin_creates_name">
<!--            <div class="admin_first_name">-->
              <%#= form.label :First %>
              <br/>
              <%= form.text_field :first_name, placeholder: "First" %>
<!--            </div>-->

<!--            <div class="admin_last_name">-->
              <%#= form.label :Last %>
              <br/>
              <%= form.text_field :last_name, placeholder: "Last" %>
            </div>
<!--          </div>-->
          <br>

          <div class="admin_creates_emailphone">
<!--            <div class="admin_email">-->
              <%#= form.label :email %>
              <br/>
              <%= form.email_field :email, placeholder: "Email", autofocus: true, autocomplete: "email" %>
<!--            </div>-->

<!--            <div class=admin_phone">-->
              <%#= form.label :number %>
              <br/>
              <%= form.text_field :phone, placeholder: "Phone" %>
<!--            </div>-->
          </div>

          <br>

          <div class="admin_creates_pass">
<!--            <div class="admin_password">-->
              <%#= form.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br/>
              <%= form.password_field :password, placeholder: "Password", autocomplete: "new-password" %>
<!--            </div>-->
          </div>

          <div class="admin_creates_roles">
            <%#= form_with(model: @user) do |form| %>
            <%#= form.collection_check_boxes :role_ids, Role.all, :id, :name %>
            <%#= @user.errors[:roles] %>
            <p class="flash"><%= flash.notice %></p>
            <%= form.submit "Create user" %>

            <%# end %>
          </div>
          </div>
        <% end %>


          </div>

          </div>


          </div>







<!--        </div>-->